# Generated by Django 6.0.3 on 2026-03-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_commission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providercommissionentry',
            options={'ordering': ['provider_name', 'degree_level']},
        ),
        migrations.RemoveField(
            model_name='providercommissionentry',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='providercommissionentry',
            name='provider_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='providercommissionentry',
            name='territory',
            field=models.TextField(blank=True, default=''),
        ),
    ]
