# Generated by Django 6.0.3 on 2026-03-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_commission', '0002_alter_providercommissionentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercommissionentry',
            name='sub_agent_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
