# Generated by Django 6.0.3 on 2026-03-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_commission', '0003_providercommissionentry_sub_agent_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCommissionAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=64)),
                ('old_value', models.CharField(blank=True, default='', max_length=255)),
                ('new_value', models.CharField(blank=True, default='', max_length=255)),
                ('changed_by', models.IntegerField(blank=True, null=True)),
                ('changed_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provider_commission_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
