# Generated by Django 6.0.3 on 2026-03-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_commission', '0004_providercommissionauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercommissionauditlog',
            name='changed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
