# Generated by Django 6.0.3 on 2026-03-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_commission', '0005_alter_providercommissionauditlog_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercommissionentry',
            name='followup_study_level',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='providercommissionentry',
            name='followup_year_rates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providercommissionentry',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='providercommissionentry',
            name='degree_level',
            field=models.CharField(default='any', max_length=255),
        ),
    ]
