# Generated by Django 6.0.3 on 2026-03-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_add_tax_slab_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='bonus_type',
            field=models.CharField(choices=[('festival', 'Festival Bonus'), ('dashain', 'Dashain Bonus'), ('performance', 'Performance Bonus'), ('target', 'Target Achievement Bonus'), ('attendance', 'Attendance Bonus'), ('referral', 'Referral Bonus'), ('joining', 'Joining Bonus'), ('retention', 'Retention Bonus'), ('commission', 'Commission Incentive'), ('yearly', 'Year-End Bonus'), ('special', 'Special Bonus'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
