# Generated by Django 6.0.3 on 2026-03-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_enhance_bonus_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(default='NPR', max_length=8),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('processed', 'Processed'), ('approved', 'Approved'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=24),
        ),
    ]
