# Generated by Django 6.0.3 on 2026-03-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_add_org_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='pan_label',
            field=models.CharField(default='PAN No.', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_label',
            field=models.CharField(default='Registration No.', max_length=64),
        ),
    ]
