# Generated by Django 6.0.3 on 2026-03-26 04:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_add_org_custom_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTaxLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100, unique=True)),
                ('tax_id_label', models.CharField(default='Tax ID No.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hrms_country_tax_labels',
                'ordering': ['country'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='taxslab',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
