# Generated by Django 6.0.3 on 2026-03-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_add_country_tax_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='view_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
