# Generated by Django 6.0.3 on 2026-03-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0008_add_payslip_view_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='no_checkout_email_subject',
            field=models.CharField(default='Missing Check-Out Notification', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='no_checkout_email_template',
            field=models.TextField(default='Dear {employee_name},\n\nThis is to notify you that you checked in at {check_in_time} on {date} but did not check out. Please ensure you check out at the end of your working hours.\n\nRegards,\nHR Department'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='no_checkout_notify_employee',
            field=models.BooleanField(default=True),
        ),
    ]
