# Generated by Django 6.0.3 on 2026-03-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_add_no_checkout_notification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='cc_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated CC email addresses for attendance notifications'),
        ),
    ]
