# Generated by Django 6.0.3 on 2026-03-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_add_cc_emails_to_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='advance_notice_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='require_cover_after_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='require_cover_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='cover_person_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
