# Generated by Django 6.0.3 on 2026-03-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0011_leavepolicy_advance_notice_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='min_advance_days',
            field=models.IntegerField(default=0),
        ),
    ]
