# Generated by Django 6.0.3 on 2026-03-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0012_add_min_advance_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='week_off_day',
            field=models.IntegerField(default=6, help_text='Day of week that is off: 0=Monday..6=Sunday'),
        ),
    ]
