# Generated by Django 6.0.3 on 2026-03-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0013_add_working_days_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_timezone',
            field=models.CharField(blank=True, help_text='IANA timezone e.g. Asia/Kathmandu, Australia/Sydney', max_length=64, null=True),
        ),
    ]
