# Generated by Django 6.0.3 on 2026-03-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_add_hr_policies_and_document_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='eligibility',
            field=models.CharField(choices=[('any', 'Any Employee'), ('terminated', 'Terminated/Resigned Only'), ('active', 'Active Employees Only')], default='any', max_length=16),
        ),
        migrations.AddField(
            model_name='hrpolicy',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrpolicy',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
