# Generated by Django 6.0.3 on 2026-03-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0017_add_policy_file_and_template_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='hide_balance_from_employee',
            field=models.BooleanField(default=False),
        ),
    ]
