# Generated by Django 6.0.3 on 2026-03-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0018_add_hide_balance_from_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='paid_leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='unpaid_leave_days',
            field=models.IntegerField(default=0),
        ),
    ]
