# Generated by Django 6.0.3 on 2026-03-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='captcha_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
