# Generated by Django 6.0.3 on 2026-03-18 01:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.UUIDField()),
                ('template_id', models.UUIDField(blank=True, null=True)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('clauses', models.JSONField(default=list)),
                ('status', models.CharField(default='draft', max_length=24)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True, null=True)),
                ('signing_token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_pdf_url', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employment_agreements',
                'ordering': ['-created_at'],
            },
        ),
    ]
