# Generated by Django 6.0.3 on 2026-03-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentagreement',
            name='manually_signed_pdf_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentagreement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentagreement',
            name='salary_currency',
            field=models.CharField(default='NPR', max_length=3),
        ),
        migrations.AlterField(
            model_name='employmentagreement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent for Signing'), ('awaiting_signature', 'Awaiting Signature'), ('signed', 'Signed'), ('manually_signed', 'Manually Signed'), ('completed', 'Completed'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=24),
        ),
    ]
