# Generated by Django 6.0.3 on 2026-03-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_agreements', '0002_employmentagreement_manually_signed_pdf_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentagreement',
            name='pdf_password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
