# Generated by Django 6.0.3 on 2026-03-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_agreements', '0003_add_pdf_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentagreement',
            name='company_signature_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentagreement',
            name='company_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentagreement',
            name='company_signer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employmentagreement',
            name='company_signer_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
