# Generated by Django 6.0.3 on 2026-03-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_agreements', '0004_add_company_signature_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentagreement',
            name='company_entity',
            field=models.CharField(choices=[('nepal', 'Study Info Centre Pvt. Ltd.'), ('australia', 'Study Info Centre Pty Ltd')], default='nepal', max_length=24),
        ),
    ]
