# Generated by Django 6.0.3 on 2026-03-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_agreements', '0005_add_company_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentagreement',
            name='company_esignature_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentagreement',
            name='esignature_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
