# Generated by Django 6.0.3 on 2026-03-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementtemplate',
            name='template_type',
            field=models.CharField(choices=[('agreement', 'Employment Agreement'), ('offer_letter', 'Job Offer Letter')], default='agreement', max_length=24),
        ),
    ]
