# Generated by Django 6.0.3 on 2026-03-18 01:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.UUIDField()),
                ('category', models.CharField(choices=[('cv', 'CV / Resume'), ('citizenship', 'Citizenship Certificate'), ('tax', 'Tax / PAN Document'), ('academic', 'Academic Certificates'), ('other', 'Other Documents')], max_length=24)),
                ('file_name', models.CharField(max_length=255)),
                ('original_file_name', models.CharField(max_length=255)),
                ('file_url', models.TextField()),
                ('file_size', models.IntegerField(default=0)),
                ('uploaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
