# Generated by Django 6.0.3 on 2026-03-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='file_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='category',
            field=models.CharField(choices=[('id_passport', 'ID / Passport'), ('contract_agreement', 'Contract / Agreement'), ('offer_letter', 'Offer Letter'), ('joining', 'Joining Documents'), ('cv', 'CV / Resume'), ('citizenship', 'Citizenship Certificate'), ('tax', 'Tax / PAN Document'), ('academic', 'Academic Certificates'), ('other', 'Other Documents')], max_length=24),
        ),
    ]
