# Generated by Django 6.0.3 on 2026-03-18 01:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.UUIDField()),
                ('template_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(default='Job Offer Letter', max_length=255)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('proposed_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='NPR', max_length=3)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('work_location', models.CharField(blank=True, max_length=255, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=128, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('probation_period', models.CharField(blank=True, max_length=128, null=True)),
                ('clauses', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('manually_signed', 'Manually Signed'), ('completed', 'Completed')], default='draft', max_length=24)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('signed_pdf_url', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offer_letters',
                'ordering': ['-created_at'],
            },
        ),
    ]
