# Generated by Django 6.0.3 on 2026-03-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='company_entity',
            field=models.CharField(default='nepal', max_length=24),
        ),
    ]
