# Generated by Django 6.0.3 on 2026-03-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_letters', '0002_add_company_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='company_esignature_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='company_signature_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='company_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='company_signer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='company_signer_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='esignature_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='manually_signed_pdf_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='pdf_password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='signing_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('employee_signed', 'Employee Signed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('signed', 'Signed'), ('manually_signed', 'Manually Signed'), ('completed', 'Completed')], default='draft', max_length=24),
        ),
    ]
