# Generated by Django 6.0.3 on 2026-03-18 01:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('citizenship_no', models.CharField(blank=True, max_length=64, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=64, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['full_name'],
            },
        ),
    ]
