# Generated by Django 6.0.3 on 2026-03-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_currency',
            field=models.CharField(choices=[('NPR', 'NPR - Nepalese Rupee'), ('AUD', 'AUD - Australian Dollar'), ('USD', 'USD - US Dollar'), ('GBP', 'GBP - British Pound'), ('CAD', 'CAD - Canadian Dollar'), ('BDT', 'BDT - Bangladeshi Taka'), ('EUR', 'EUR - Euro'), ('NZD', 'NZD - New Zealand Dollar')], default='NPR', max_length=3),
        ),
    ]
