# Generated by Django 6.0.3 on 2026-03-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_salary_amount_employee_salary_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
