# Generated by Django 6.0.3 on 2026-03-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_bank_account_number_employee_bank_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
