# Generated by Django 6.0.3 on 2026-03-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_add_employee_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
