# Generated by Django 6.0.3 on 2026-03-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_add_employee_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='working_days_per_week',
            field=models.IntegerField(blank=True, help_text='Override department default: 5 or 6', null=True),
        ),
    ]
