# Generated by Django 6.0.3 on 2026-03-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_add_working_days_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='week_off_days',
            field=models.JSONField(blank=True, help_text='List of week-off day numbers: 0=Mon..6=Sun, e.g. [5,6] for Sat+Sun', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_end_time',
            field=models.TimeField(blank=True, help_text='Override department work end time', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_start_time',
            field=models.TimeField(blank=True, help_text='Override department work start time', null=True),
        ),
    ]
